---
- name: The Silly Radio
  hosts: radio
  become: true

  vars:
    number_of_radios: 25

  tasks:
    - name: Set up the incomplete dirs
      file:
        path: /mnt/radio/incomplete{{ item }}
        owner: root
        group: root
        mode: 0777
        state: directory
      with_sequence: start=1 count={{ number_of_radios }}

    - name: Set up the download dirs on MooseFS
      file:
        path: /mnt/mfs/services/radio/final{{ item }}
        owner: root
        group: root
        mode: 0777
        state: directory
      with_sequence: start=1 count={{ number_of_radios }}

    - name: Set up the download dirs
      file:
        src: /mnt/mfs/services/radio/final{{ item }}
        dest: /mnt/radio/download{{ item }}
        owner: root
        group: root
        mode: 0777
        state: link
      with_sequence: start=1 count={{ number_of_radios }}

    - name: Set up the watch dirs
      file:
        path: /mnt/radio/watch{{ item }}
        owner: root
        group: root
        mode: 0777
        state: directory
      with_sequence: start=1 count={{ number_of_radios }}
