---
- name: The Silly Radio
  hosts: radio
  become: true

  vars:
    number_of_radios: 25

  tasks:
    - name: Create the media user
      ansible.builtin.user:
        name: media
        comment: Media
        uid: 1003

    - name: Set up the incomplete dirs
      file:
        path: /mnt/radio/incomplete{{ item }}
        owner: media
        group: media
        mode: 0777
        state: directory
      with_sequence: start=1 count={{ number_of_radios }}

    - name: Set up the download dirs
      file:
        path: /mfsbrick.3/final{{ item }}
        owner: media
        group: media
        mode: 0777
        state: directory
      with_sequence: start=1 count={{ number_of_radios }}

    - name: Set up the watch dirs
      file:
        path: /mnt/radio/watch{{ item }}
        owner: media
        group: media
        mode: 0777
        state: directory
      with_sequence: start=1 count={{ number_of_radios }}
